### PR TITLE
1p0f1bj-actix-skeleton-docker-ci

### PR DESCRIPTION
**Pull request by Mik-Grzeg**
Created skeleton for the family tree api, postgresql schema, Dockerfiles for the rust apps. Configured Travis CI.

### CODE REVIEW

**Comment by MartaKirsch** [comment]
question
So I've tried to run docker-compose up from project root directory, but it cannot get done. Do I have to add some kind of env file somewhere or sth? Or maybe it should be another command to get it started? 😅 Or - maybe it just takes this long, I don't know

**Comment by Mik-Grzeg** [comment]
Rust is known for long compilation time especiqlly with `--release` flag. However it seems like its stuck at copying content of the fam... directory. I'll check if .dockerignore masks .target directory correctly because it might be huge. What is the os that you use ?

**Comment by MartaKirsch** [comment]
Ok, it was like 20min for me, but it finally works XD Nice 👌

**Review by MartaKirsch — APPROVED** [review]
👌

**Comment by Mik-Grzeg** [comment]
It might've been the fact that I already had installed rust tools like cargo and rust itself. Docker might have grabbed cached versions of them but I'm not sure. 
Hmu in case the problem continues in next builds.

**Pull request merged**
