### PR TITLE
1ydcgbd genealogy api definition

### PR DESCRIPTION
**Pull request by Mik-Grzeg**
There might be some conflicts with #15 PR, so after merging #15 to master I'll try to resolve them.

### CODE REVIEW

**Comment by MartaKirsch** [comment]
Ok, so the api looks nice, definitely 👍 However, it seems kind of unfinished. 

First of all we have already discussed that on the front side I have only username and token, so this path is impossible to call:
obraz
And we should correct the response data structure (Node is an individual, so our _relations_ array is Node array):
obraz
You can see the exact types here in my codesandbox: https://codesandbox.io/s/admiring-paper-ct0l2?file=/src/utils/people.ts
If you right-click on **Node** in the import on top of the page and **Go to definition**- there should be everything there.

I think we also should discuss this one. 
If we want to store the whole tree personal data (hometown, job, hobbies, etc - everything) on the frontend - then we could just attach all the data to the **/tree** endpoint response. 
If we want to send only necessary info in the initial request ( **/tree** and get full name, id and date of birth), and then one request for more detailed info when opening the info modal - this endpoint seems unnecessary
obraz

Also, there are some endpoints without the request body structure - we can merge this pr and add it later on though. 
**I think that before merging it we should at least agree on some crucial requests for now:**
1. getting the tree structure when user logs in (either whole data with hobbies, job, etc OR just the necessary data)
2. adding a new person to the tree. For this - frontend for now is ready for something like this:

row

Of course we can change the exact structure, but it's important that for now I have:
1. Full name input (required, you have to enter at least two words separated by space)
2. Hometown input (required)
3. Date of birth input (required, cannot enter date after 'now')
4. Date of death input (not required, cannot enter date after 'now')
5. Job input (not required)
6. Hobbies input (not required or string array)
7. Relation (required if modal was opened from person tile - if was opened from "Add first family member" tile it's not present)
8. Images (not required, accepts pngs and jpgs)
While we're at it, I would have to know the database length constraints for front validation and what changes are necessary (if any). Because you would have to take it into account while writing the api requests' body structure 😅

**Comment by Mik-Grzeg** [comment]
That's right, api is still a work in progress.
I am not sure what's wrong with the Node. Is it gender and boolean or rel_type instead of type in Relation?

Im planning to create endpoint for adding an individual to a tree 

According to the section with individuals's information, I think separate endpoint for detailed information about an individual would be more appropriate. Because having many individuals in a tree could potentially slow down loading/fetching the tree. 

I'll add the detailed information to the the database etc. and remove /individuals

**Comment by MartaKirsch** [comment]
In the response of **/tree** endpoint there should be **id (string)** rather than **individual (int)**.  Also, the **gender** is not optional - it has to be a string **"female"** or **"male"**. In the relations (siblings, parents, etc) there should be **type (string)** written lowercase rather than **rel_type (string)**, and the **id** should be string as well. The **placeholder (boolean)** is optional and I don't think we need it 😅

If you want this pr to be only for creating the api docs (and change the requests in separate prs) I think we can merge it o.o 

We can make a call on Teams sometime to talk about the stored individual's data (therefore, about the add-individual request body) because I think it's difficult to understand each other through writing 🤣 I could show you the current add-form, because I think it's ready for now - I need to know about the data and length constraints, then I could update it and the tests, and then just connect it to the backend o.o

**Comment by MartaKirsch** [comment]
I checked out the branch for this pr, ran ```git pull origin``` and there are some conflicts 
obraz
What should I do? 😅 If I run ```git branch -d <branch_name>``` and pull the whole branch again, should it be alright? Because I don't want to delete something by accident 😂

**Comment by MartaKirsch** [comment]
Screenshot 2022-01-06 at 09-29-31 Swagger UI
On the frontend I have only one input for **full name** and we have discussed it already 😅 It has validation for having *some_text* [space] *some_text*. And the hometown (required on the frontend to submit the form), job (not required), hobbies (not required), date of birth (required), date of death (not required)? And also - except for the first person in the tree, it will come with a **relative_id** (or something like this) and **relation** (_"parent"_, "_child_", "_adopted child_", etc).

Screenshot 2022-01-06 at 09-35-31 Swagger UI
And here - in the **/tree/{username}** - relation **type** should be written lowercase - **"blood"** instead of **"Blood"**.
In the **infos**, the **id** should also be a **string**, as it would be used to match the two arrays. There should be a **full name** instead of **first name** and **last name**, and the **date of birth** is missing. If there is any image saved for the person, it would be nice if it came with one **img url** as well.

**Comment by MartaKirsch** [comment]
obraz
Do I undarstand it correctly? Let's say we click on **Mister X** to add his relative.
We have **role to relative** which says who the newly added person would be for Mister X, and the **relatives role** works the other way around? If so, can't we just send one of those (the frontend has **role to relative** as of now)?

**Comment by Mik-Grzeg** [comment]
Right it should be parent and child. It necessary for creating new relation. I suppose it could somehow be automatically filled, but I haven't implemented that.

**Comment by Mik-Grzeg** [comment]
That's all, if that's an inconvenience for you I can implement that on my part. You decide

**Comment by MartaKirsch** [comment]
I think it would be better to avoid sending over unnecessary data and just do it on the backend, but I also feel like I complain too much XD

**Comment by Mik-Grzeg** [comment]
:+1: now it's just the role of the person that is created, the same thing changed for creating new relation without adding people.

**Review by MartaKirsch — APPROVED** [review]

**Pull request merged**
